kanji/073cd-VtLst.svg, kanji/073cd.svg
=> 073cd: swap original/element for group 1

kanji/08332.svg
This fixes an error in numbering pointed out in https://github.com/KanjiVG/kanjivg.github.com/issues/2
=> Fix numbering error

kanji/056e3.svg, kanji/08853.svg
See https://github.com/KanjiVG/kanjivg/issues/220
=> Replace all kamae1 and kamae2 position types with kamae

kanji/09ef7.svg
https://github.com/KanjiVG/kanjivg/issues/222
=> Alter 09ef7 to use 四 for the central right element

kanji/201a2.svg
https://github.com/KanjiVG/kanjivg/issues/130
=> Add ospalh's version of U+201a2

kanji/04f34-HzFst.svg
Resolves https://github.com/KanjiVG/kanjivg/issues/216
=> Add numbers & rename 04e0a-HzFst to 04f34-HzFst

kanji/072ad.svg
https://github.com/KanjiVG/kanjivg/issues/135
=> Add 072ad.svg

kanji/0353e.svg
See https://github.com/KanjiVG/kanjivg/issues/133
=> Add 03533.svg

kanji/06d32.svg, kanji/0916c-Kaisho.svg, kanji/0916c.svg, kanji/099f2-Vt6.svg, kanji/099f2.svg
This fixes https://github.com/KanjiVG/kanjivg/issues/252
=> Add part="3" where missing on 川 elements

kanji/04f7b-MidFst.svg, kanji/04f7b.svg, kanji/059da-MidFst.svg, kanji/059da.svg, kanji/06311-MidFst.svg, kanji/06311.svg, kanji/06641-Kaisho.svg, kanji/06641-KaishoMidFst.svg, kanji/06641.svg, kanji/06843-Kaisho.svg, kanji/06843-KaishoMidFst.svg, kanji/06843.svg, kanji/0773a-Kaisho.svg, kanji/0773a-KaishoMidFst.svg, kanji/0773a.svg, kanji/07a95-Kaisho.svg, kanji/07a95-KaishoMidFst.svg, kanji/07a95.svg, kanji/08a82-MidFst.svg, kanji/08a82.svg, kanji/08df3-MidFst.svg, kanji/08df3.svg, kanji/09003-MidFst.svg, kanji/09003.svg, kanji/0929a-MidFst.svg, kanji/0929a.svg
This should fix the fifth issue mentioned here:
https://github.com/KanjiVG/kanjivg/issues/128
=> Fix the groups on 兆 elements

kanji/02ec3.svg
https://github.com/KanjiVG/kanjivg/issues/139
=> Add 02ec3.svg radical

kanji/053db.svg
I removed a 十 group, it's hard to know what to do with these.
=> Fix groups in 053db.svg

kanji/07e96-Kaisho.svg
See https://github.com/KanjiVG/kanjivg/issues/297
=> Fix up 07e96-Kaisho.svg

kanji/07e8e-Kaisho.svg
The last six strokes were made the first six, a number was added for
stroke 21, and strokes 7 and 8 were swapped. I checked the stroke
order here:
https://kakijun.jp/page/E39A200.html
=> Fix 07e8e-Kaisho.svg

kanji/0677e.svg
Should fix https://github.com/KanjiVG/kanjivg/issues/166
=> Copy stroke 6 of 0677e from the kaisho variant

kanji/02ec3.svg, kanji/0353e.svg, kanji/052d7-Kaisho.svg, kanji/0658e-Kaisho.svg, kanji/0658e-KaishoMdFst.svg, kanji/0658e-KaishoVt6.svg, kanji/06ed5-Kaisho.svg, kanji/072ad.svg, kanji/07f86-Kaisho.svg, kanji/0962f-HzFst.svg, kanji/09918-Kaisho.svg, kanji/09f21-Kaisho.svg
This should do https://github.com/KanjiVG/kanjivg/issues/314.
=> Add missing radicals to characters

kanji/066f2-Kaisho.svg, kanji/066f2-KaishoVtLst.svg, kanji/066f2.svg
Also remove a lot of small groups containing only one path which
seemed to have caused the creator of this file much confusion.
Also put the Nelson radical on the correct stroke
=> Add the centre horizontal to the radical group

kanji/02e89.svg
=> Add CJK Radicals Supplement ⺉

kanji/02ead.svg
=> Add CJK Radicals Supplement ⺭

kanji/09dd7-Kaisho.svg, kanji/09dd7.svg
- Added missing stroke order numbers for character 鷗 (09dd7, 09dd7-Kaisho)
Thanks @benkasminbullock for maintaining this awesome project.
=> Fix 09dd7 - add missing stroke numbers

kanji/05c28.svg
This brings it up to paraty with 尤 and allows scripts to extract the correct nelson radical.
=> Add the 丶 group to 尨
